# Generated by Django 5.0.6 on 2025-10-27 20:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(default='unknown', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContainerRegistry',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('provider', models.CharField(choices=[('acr', 'Azure Container Registry'), ('gcr', 'Google Container Registry'), ('jfrog', 'JFrog Artifactory'), ('dockerhub', 'Docker Hub'), ('harbor', 'Harbor')], max_length=32)),
                ('api_url', models.URLField(blank=True, null=True)),
                ('login', models.CharField(blank=True, max_length=128)),
                ('password', models.CharField(blank=True, max_length=256)),
                ('token', models.TextField(blank=True, null=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Registry',
                'verbose_name_plural': 'Registry',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('digest', models.CharField(blank=True, max_length=255, null=True)),
                ('artifact_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('sbom_data', models.JSONField(blank=True, null=True)),
                ('grype_data', models.JSONField(blank=True, null=True)),
                ('scan_status', models.CharField(choices=[('pending', 'Pending'), ('in_process', 'In Process'), ('success', 'Success'), ('error', 'Error'), ('none', 'None')], default='none', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Release',
                'verbose_name_plural': 'Releases',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComponentVersion',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=255)),
                ('latest_version', models.CharField(blank=True, max_length=255, null=True)),
                ('latest_version_updated_at', models.DateTimeField(blank=True, null=True)),
                ('purl', models.CharField(blank=True, max_length=512, null=True)),
                ('cpes', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.component')),
                ('images', models.ManyToManyField(blank=True, related_name='component_versions', to='core.image')),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.BooleanField(blank=True, default=False, verbose_name='Status')),
                ('last_scanned', models.DateTimeField(blank=True, null=True)),
                ('scan_status', models.CharField(choices=[('pending', 'Pending'), ('in_process', 'In Process'), ('success', 'Success'), ('error', 'Error'), ('none', 'None')], default='none', max_length=32)),
                ('repository_type', models.CharField(choices=[('helm', 'Helm Chart'), ('docker', 'Docker Image'), ('none', 'Unknown')], default='none', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('container_registry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='core.containerregistry')),
            ],
            options={
                'verbose_name_plural': 'Repositories',
                'unique_together': {('name', 'url')},
            },
        ),
        migrations.CreateModel(
            name='RepositoryTag',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=255)),
                ('digest', models.CharField(blank=True, max_length=255, null=True)),
                ('processing_status', models.CharField(choices=[('pending', 'Pending'), ('in_process', 'In Process'), ('success', 'Success'), ('error', 'Error'), ('none', 'None')], default='none', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.repository')),
            ],
            options={
                'unique_together': {('tag', 'repository')},
            },
        ),
        migrations.AddField(
            model_name='image',
            name='repository_tags',
            field=models.ManyToManyField(blank=True, related_name='images', to='core.repositorytag'),
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vulnerability_id', models.CharField(max_length=255, unique=True)),
                ('vulnerability_type', models.CharField(default='CVE', max_length=50)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('UNKNOWN', 'Unknown')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('epss', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vulnerability',
                'verbose_name_plural': 'Vulnerabilities',
                'unique_together': {('vulnerability_id',)},
            },
        ),
        migrations.CreateModel(
            name='ComponentVersionVulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixable', models.BooleanField(default=False, help_text='True if a fix is available for this vulnerability in this component version')),
                ('fix', models.CharField(blank=True, help_text='Fix version(s) or state from Grype report', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.componentversion')),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vulnerability')),
            ],
            options={
                'verbose_name': 'Component Version Vulnerability Link',
                'verbose_name_plural': 'Component Version Vulnerability Links',
                'unique_together': {('component_version', 'vulnerability')},
            },
        ),
        migrations.AddField(
            model_name='componentversion',
            name='vulnerabilities',
            field=models.ManyToManyField(blank=True, related_name='component_versions', through='core.ComponentVersionVulnerability', to='core.vulnerability'),
        ),
        migrations.CreateModel(
            name='VulnerabilityDetails',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cve_details_score', models.FloatField(blank=True, help_text='CVSS Score from CVE Details', null=True)),
                ('cve_details_severity', models.CharField(blank=True, help_text='Severity from CVE Details', max_length=20, null=True)),
                ('cve_details_published_date', models.DateField(blank=True, help_text='Published date from CVE Details', null=True)),
                ('cve_details_updated_date', models.DateField(blank=True, help_text='Last updated date from CVE Details', null=True)),
                ('cve_details_summary', models.TextField(blank=True, help_text='Detailed summary from CVE Details', null=True)),
                ('cve_details_references', models.JSONField(blank=True, default=list, help_text='References from CVE Details')),
                ('exploit_available', models.BooleanField(default=False, help_text='Whether exploit is publicly available')),
                ('exploit_public', models.BooleanField(default=False, help_text='Whether exploit is in public databases')),
                ('exploit_verified', models.BooleanField(default=False, help_text='Whether exploit has been verified')),
                ('exploit_links', models.JSONField(blank=True, default=list, help_text='Links to exploit information')),
                ('cisa_kev_known_exploited', models.BooleanField(default=False, help_text='Whether vulnerability is in CISA KEV catalog')),
                ('cisa_kev_date_added', models.DateField(blank=True, help_text='Date added to CISA KEV catalog', null=True)),
                ('cisa_kev_vendor_project', models.CharField(blank=True, help_text='Vendor/Project from CISA KEV', max_length=255, null=True)),
                ('cisa_kev_product', models.CharField(blank=True, help_text='Product from CISA KEV', max_length=255, null=True)),
                ('cisa_kev_vulnerability_name', models.CharField(blank=True, help_text='Vulnerability name from CISA KEV', max_length=255, null=True)),
                ('cisa_kev_short_description', models.TextField(blank=True, help_text='Short description from CISA KEV', null=True)),
                ('cisa_kev_required_action', models.TextField(blank=True, help_text='Required action from CISA KEV', null=True)),
                ('cisa_kev_due_date', models.DateField(blank=True, help_text='Due date from CISA KEV', null=True)),
                ('cisa_kev_ransomware_use', models.CharField(blank=True, help_text='Known ransomware campaign use', max_length=20, null=True)),
                ('cisa_kev_notes', models.TextField(blank=True, help_text='Notes from CISA KEV', null=True)),
                ('cisa_kev_cwes', models.JSONField(blank=True, default=list, help_text='CWE codes from CISA KEV')),
                ('exploit_db_available', models.BooleanField(default=False, help_text='Whether exploit is available in Exploit-DB')),
                ('exploit_db_verified', models.BooleanField(default=False, help_text='Whether exploit is verified in Exploit-DB')),
                ('exploit_db_count', models.IntegerField(default=0, help_text='Number of exploits found in Exploit-DB')),
                ('exploit_db_verified_count', models.IntegerField(default=0, help_text='Number of verified exploits in Exploit-DB')),
                ('exploit_db_working_count', models.IntegerField(default=0, help_text='Number of working exploits in Exploit-DB')),
                ('exploit_db_links', models.JSONField(blank=True, default=list, help_text='Links to Exploit-DB entries')),
                ('last_updated', models.DateTimeField(auto_now=True, help_text='When this record was last updated')),
                ('data_source', models.CharField(default='manual', help_text='Source of this information', max_length=100)),
                ('epss_score', models.FloatField(blank=True, help_text='EPSS score from FIRST API', null=True)),
                ('epss_percentile', models.FloatField(blank=True, help_text='EPSS percentile from FIRST API', null=True)),
                ('epss_date', models.DateField(blank=True, help_text='EPSS assessment date from FIRST API', null=True)),
                ('epss_data_source', models.CharField(blank=True, help_text='Source of EPSS data (FIRST-EPSS, Grype, etc.)', max_length=50, null=True)),
                ('epss_last_updated', models.DateTimeField(blank=True, help_text='When EPSS data was last updated', null=True)),
                ('vulnerability', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='core.vulnerability')),
            ],
            options={
                'verbose_name': 'Vulnerability Details',
                'verbose_name_plural': 'Vulnerability Details',
            },
        ),
        migrations.CreateModel(
            name='ComponentLocation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(help_text='File path where component was found', max_length=512)),
                ('layer_id', models.CharField(blank=True, help_text='Docker layer ID', max_length=255, null=True)),
                ('access_path', models.CharField(blank=True, help_text='Access path to the component', max_length=512, null=True)),
                ('evidence_type', models.CharField(choices=[('primary', 'Primary Evidence'), ('supporting', 'Supporting Evidence'), ('unknown', 'Unknown')], default='unknown', help_text='Type of evidence for this location', max_length=32)),
                ('annotations', models.JSONField(blank=True, default=dict, help_text='Additional annotations from Grype')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.componentversion')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_locations', to='core.image')),
            ],
            options={
                'verbose_name': 'Component Location',
                'verbose_name_plural': 'Component Locations',
                'indexes': [models.Index(fields=['path'], name='core_compon_path_5c2a21_idx'), models.Index(fields=['layer_id'], name='core_compon_layer_i_2a0099_idx'), models.Index(fields=['evidence_type'], name='core_compon_evidenc_81c870_idx')],
                'unique_together': {('component_version', 'image', 'path')},
            },
        ),
        migrations.CreateModel(
            name='RepositoryTagRelease',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository_tags', to='core.release')),
                ('repository_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='core.repositorytag')),
            ],
            options={
                'verbose_name': 'Repository Tag Release Assignment',
                'verbose_name_plural': 'Repository Tag Release Assignments',
                'unique_together': {('repository_tag', 'release')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='componentversion',
            unique_together={('version', 'component')},
        ),
    ]
