# Generated by Django 5.0.6 on 2025-06-01 21:40

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(default='unknown', max_length=50)),
                ('purl', models.CharField(blank=True, max_length=255, null=True)),
                ('cpes', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContainerRegistry',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('provider', models.CharField(choices=[('acr', 'Azure Container Registry'), ('gcr', 'Google Container Registry'), ('jfrog', 'JFrog Artifactory'), ('dockerhub', 'Docker Hub'), ('harbor', 'Harbor')], max_length=32)),
                ('api_url', models.URLField(blank=True, null=True)),
                ('login', models.CharField(blank=True, max_length=128)),
                ('password', models.CharField(blank=True, max_length=256)),
                ('token', models.TextField(blank=True, null=True)),
                ('last_sync', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Registry',
                'verbose_name_plural': 'Registry',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('digest', models.CharField(blank=True, max_length=255, null=True)),
                ('artifact_reference', models.CharField(blank=True, max_length=255, null=True)),
                ('sbom_data', models.JSONField(blank=True, null=True)),
                ('grype_data', models.JSONField(blank=True, null=True)),
                ('scan_status', models.CharField(choices=[('pending', 'Pending'), ('in_process', 'In Process'), ('success', 'Success'), ('error', 'Error'), ('none', 'None')], default='none', max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ComponentVersion',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='core.component')),
                ('images', models.ManyToManyField(blank=True, related_name='component_versions', to='core.image')),
            ],
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.BooleanField(blank=True, default=False, verbose_name='Status')),
                ('last_scanned', models.DateTimeField(blank=True, null=True)),
                ('repository_type', models.CharField(choices=[('helm', 'Helm Chart'), ('docker', 'Docker Image')], default='docker', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('container_registry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to='core.containerregistry')),
            ],
            options={
                'verbose_name_plural': 'Repositories',
                'unique_together': {('name', 'url')},
            },
        ),
        migrations.CreateModel(
            name='RepositoryTag',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=255)),
                ('digest', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('repository', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.repository')),
            ],
            options={
                'unique_together': {('tag', 'repository')},
            },
        ),
        migrations.AddField(
            model_name='image',
            name='repository_tags',
            field=models.ManyToManyField(blank=True, related_name='images', to='core.repositorytag'),
        ),
        migrations.CreateModel(
            name='Vulnerability',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vulnerability_id', models.CharField(max_length=255, unique=True)),
                ('vulnerability_type', models.CharField(default='CVE', max_length=50)),
                ('severity', models.CharField(choices=[('CRITICAL', 'Critical'), ('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low'), ('UNKNOWN', 'Unknown')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('epss', models.FloatField(default=0.0)),
                ('fixable', models.BooleanField(default=False, help_text='True if a fix is available for this vulnerability')),
                ('fix', models.CharField(blank=True, help_text='Fix version(s) or state from Grype report', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('vulnerability_id',)},
            },
        ),
        migrations.CreateModel(
            name='ComponentVersionVulnerability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixable', models.BooleanField(default=False, help_text='True if a fix is available for this vulnerability in this component version')),
                ('fix', models.CharField(blank=True, help_text='Fix version(s) or state from Grype report', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.componentversion')),
                ('vulnerability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vulnerability')),
            ],
            options={
                'verbose_name': 'Component Version Vulnerability Link',
                'verbose_name_plural': 'Component Version Vulnerability Links',
                'unique_together': {('component_version', 'vulnerability')},
            },
        ),
        migrations.AddField(
            model_name='componentversion',
            name='vulnerabilities',
            field=models.ManyToManyField(blank=True, related_name='component_versions', through='core.ComponentVersionVulnerability', to='core.vulnerability'),
        ),
        migrations.AlterUniqueTogether(
            name='componentversion',
            unique_together={('version', 'component')},
        ),
    ]
