# Generated by Django 5.0.6 on 2025-06-09 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_vulnerability_options_remove_vulnerability_fix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repository',
            name='repository_type',
            field=models.CharField(choices=[('helm', 'Helm Chart'), ('docker', 'Docker Image'), ('none', 'Unknown')], default='none', max_length=10),
        ),
    ]
