# Generated by Django 5.0.6 on 2025-06-10 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_repository_repository_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='repository',
            name='scan_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_process', 'In Process'), ('success', 'Success'), ('error', 'Error'), ('none', 'None')], default='none', max_length=32),
        ),
    ]
