# Generated by Django 5.0.6 on 2025-06-10 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_repository_scan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='repositorytag',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_process', 'In Process'), ('success', 'Success'), ('error', 'Error'), ('none', 'None')], default='none', max_length=32),
        ),
    ]
