# Generated by Django 5.0.6 on 2025-06-13 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_repositorytag_processing_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='component',
            name='cpes',
        ),
        migrations.RemoveField(
            model_name='component',
            name='purl',
        ),
    ]
