# Generated by Django 5.0.6 on 2025-06-13 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_component_cpes_remove_component_purl'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentversion',
            name='cpes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='componentversion',
            name='purl',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
