# Generated by Django 5.0.6 on 2025-06-13 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_componentversion_cpes_componentversion_purl'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentversion',
            name='latest_version',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
