# Generated by Django 5.0.6 on 2025-06-13 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_componentversion_latest_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentversion',
            name='latest_version_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
