# Generated by Django 5.0.6 on 2025-07-31 19:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_componentversion_latest_version_updated_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Release',
                'verbose_name_plural': 'Releases',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RepositoryTagRelease',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repository_tags', to='core.release')),
                ('repository_tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='core.repositorytag')),
            ],
            options={
                'verbose_name': 'Repository Tag Release Assignment',
                'verbose_name_plural': 'Repository Tag Release Assignments',
                'unique_together': {('repository_tag', 'release')},
            },
        ),
    ]
