# Generated by Django 5.0.6 on 2025-08-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_release_repositorytagrelease'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='name',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
