# Generated by Django 5.0.6 on 2025-08-07 18:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_vulnerabilitydetails_exploit_db_available_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComponentLocation',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('path', models.CharField(help_text='File path where component was found', max_length=512)),
                ('layer_id', models.CharField(blank=True, help_text='Docker layer ID', max_length=255, null=True)),
                ('access_path', models.CharField(blank=True, help_text='Access path to the component', max_length=512, null=True)),
                ('evidence_type', models.CharField(choices=[('primary', 'Primary Evidence'), ('supporting', 'Supporting Evidence'), ('unknown', 'Unknown')], default='unknown', help_text='Type of evidence for this location', max_length=32)),
                ('annotations', models.JSONField(blank=True, default=dict, help_text='Additional annotations from Grype')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('component_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='core.componentversion')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='component_locations', to='core.image')),
            ],
            options={
                'verbose_name': 'Component Location',
                'verbose_name_plural': 'Component Locations',
                'indexes': [models.Index(fields=['path'], name='core_compon_path_5c2a21_idx'), models.Index(fields=['layer_id'], name='core_compon_layer_i_2a0099_idx'), models.Index(fields=['evidence_type'], name='core_compon_evidenc_81c870_idx')],
                'unique_together': {('component_version', 'image', 'path')},
            },
        ),
    ]
