# Generated by Django 5.0.6 on 2026-09-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_clusters_and_standalone_image_registry'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='clusterimage',
            index=models.Index(fields=['cluster', 'source_reference'], name='core_climg_cluster_src_idx'),
        ),
    ]
